apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lso-app3
  namespace: openshift-gitops
spec:
  destination:
    namespace: lso-app3
    server: https://kubernetes.default.svc 
  project: default 
  source: 
    path: lso/application-manifest
    repoURL: https://github.com/mfau007/customer1
    targetRevision: main
  syncPolicy: 
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
