---
apiVersion: local.storage.openshift.io/v1alpha1
kind: LocalVolumeSet
metadata:
  name: local-ssd
  namespace: openshift-local-storage
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  deviceInclusionSpec:
    deviceMechanicalProperties:
    - NonRotational
    deviceTypes:
    - disk
    minSize: 190Gi
    maxSize: 210Gi 
  nodeSelector:
    nodeSelectorTerms:
      - matchExpressions:
        - key: cluster.ocs.openshift.io/openshift-storage
          operator: Exists
  storageClassName: local-ssd
  volumeMode: Block
