apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: odf-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: odf-app
    server: https://kubernetes.default.svc 
  project: default 
  source: 
    path: odf/application-manifest
    repoURL: https://github.com/mfau007/customer1
    targetRevision: main
  syncPolicy: 
    automated:
      prune: false
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
