apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"      
  name: ocs-storagecluster
  namespace: openshift-storage
spec:
  arbiter: {}
  encryption:
    kms: {}
  externalStorage: {}
  managedResources:
    cephBlockPools: {}
      reconcileStrategy: ignore  # added this
    cephCluster: {}
    cephConfig: {}
    cephDashboard: {}
      #    cephFilesystems: {} # commented this out
    cephNonResilientPools: {}
    cephObjectStoreUsers: {}
    cephObjectStores: {}
    cephToolbox: {}
  multiCloudGateway:
    dbStorageClassName: ocs-storagecluster-ceph-rbd-nvme # added this
  mirroring: {}
  monDataDirHostPath: /var/lib/rook
  nodeTopologies: {}
  storageDeviceSets:
  - config: {}
    count: 1 # verify with stephen
    dataPVCTemplate:
      metadata: {}
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: "1"
        storageClassName: local-hdd
        volumeMode: Block
      status: {}
    name: ocs-deviceset-local-hdd
    placement: {}
    preparePlacement: {}
    replica: 3
    deviceType: hdd # added this field
    resources: {}
  - config: {}  # added this on down for the nvme
    count: 1
    dataPVCTemplate:
      metadata: {}
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: "1"
        storageClassName: local-nvme
        volumeMode: Block
      status: {}
    name: ocs-deviceset-local-nvme
    placement: {}
    preparePlacement: {}
    replica: 3
    deviceType: nvme  #added this
    resources: {}
  version: 4.12.0
